### ISSUE TITLE
Envoyer une tof board place de marché

### ISSUE THREAD

**Issue by pointbar** [atmtp16/contributions#1]

**Comment by estrebet** [comment]
maj de la liste https://github.com/atmtp16/contributions/blob/master/materiel.md de matos avec la référence des plaques pour place de marché

**Comment by estrebet** [comment]
exemple de 4 plaques côte à côte et l'une sur l'autre
![img_2488](https://cloud.githubusercontent.com/assets/4040955/20431934/2674e092-ad9d-11e6-80ba-34aeafde4b4c.jpg)
